steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${TAG_NAME}" =~ ^release-prod-v[0-9]+$ ]]; then
          echo //registry.npmjs.org/:_authToken=$$NPM_TOKEN > .npmrc
          npm publish
        fi
    secretEnv: ['NPM_TOKEN']

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/publish_token
    secretEnv:
      NPM_TOKEN: CiQA4RDOWTcz2ld8l+Hi+PW5GA+fjljAWhRqn8/oedjwj6QQEdYSTQC6A7iWkK11ed6DKaVLLigQ8teK52clDV8zrEG915YJOfukpa+sjEeQMegtm+tE07VMs+ads8wP0K2cbdqJRYhxNQ1Zcry3qjyEVrLi
