steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base || true
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint || true
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/test || true
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build || true
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--target', 'base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--target', 'lint',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build',
    '--target', 'build',
    '.'
  ]

substitutions:
  _SLACK_NOTIFY_CHANNEL: '#triple-web-dev'
  _SVC_BASENAME: triple-frontend
  _AUTO_TAGGING_ENABLED: 'false'

images:
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base'
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build'
