steps:
  ## package release image
  - name: 'gcr.io/cloud-builders/docker'
    id: package
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --file Dockerfile.docs \
          --build-arg NPM_TOKEN \
          --tag 107243714588.dkr.ecr.ap-northeast-1.amazonaws.com/${_SVC_BASENAME}:${SHORT_SHA} \
          --tag 107243714588.dkr.ecr.ap-northeast-1.amazonaws.com/${_SVC_BASENAME}:latest \
          .
    secretEnv:
      - 'NPM_TOKEN'

  ## push release image to AWS ECR
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -sS --fail "${_OPS_API}/gcp-ecr-auth?token=$$OPS&script=1&region=ap-northeast-1" | bash
        docker push 107243714588.dkr.ecr.ap-northeast-1.amazonaws.com/${_SVC_BASENAME}:${SHORT_SHA}
        docker push 107243714588.dkr.ecr.ap-northeast-1.amazonaws.com/${_SVC_BASENAME}:latest
    secretEnv:
      - 'OPS'

  - name: 'gcr.io/cloud-builders/docker'
    id: release
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -sS --fail --max-time 60 -X POST "${_OPS_API}/gcp-ecs-deploy/triple-dev/${_SVC_BASENAME}/${SHORT_SHA}?token=$$OPS"
    secretEnv:
      - 'OPS'

substitutions:
  _OPS_API: 'https://ops.triple-corp.com/api/v1'
  _SLACK_NOTIFY_CHANNEL: '#triple-web-dev-notifications'
  _SVC_BASENAME: 'triple-frontend-docs'

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/read_only_token
    secretEnv:
      NPM_TOKEN: CiQAcBjweQp70fQdHefg3+1XUiV+kwWJc/usCYSnHK6/kceVvDISTQCQlPnJ+dwlsKOmOB5j6Wp7QkXs/zeZahCylb7nvnGgUa/1h1qlK2IppruD5XdRLmO0OzujWNDfvmjfNNtZ46CQMrPf58T1ZV0hgP/P
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/aws/cryptoKeys/ops
    secretEnv:
      OPS: CiQAI4MdjlE2q7vUiJzq4snoFOPtUIo3wD3utvp6uIvUw1sOaHsSUQBDqgoddjh/WYT0cBKxSwv2UAM+PlWooyFFF4tJ1cl20wQfa70N4AbKfF8sCwmqxu2Icc1BX9+4ODMO4kwwcDvlI1HUiD/nYQPSVywmUTUWDg==
