steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base || true
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint || true
    docker pull gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build || true
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
    - 'NPM_TOKEN'
  args: [
    'build',
    '--build-arg', 'NPM_TOKEN',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--target', 'base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
    - 'NPM_TOKEN'
  args: [
    'build',
    '--build-arg', 'NPM_TOKEN',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--target', 'lint',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
    - 'NPM_TOKEN'
  args: [
    'build',
    '--build-arg', 'NPM_TOKEN',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build',
    '--target', 'build',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
    - 'NPM_TOKEN'
  args: [
    'build',
    '--build-arg', 'NPM_TOKEN',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build',
    '--cache-from', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/test',
    '--tag', 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/test',
    '--file', './Dockerfile.test',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_8'

substitutions:
  _SLACK_NOTIFY_CHANNEL: '#triple-web-dev-notifications'
  _SVC_BASENAME: triple-frontend
  _AUTO_TAGGING_RULE: 'master=release-docs'

images:
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/base'
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/lint'
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/build'
- 'gcr.io/${PROJECT_ID}/${_SVC_BASENAME}/test'

timeout: 1600s

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/read_only_token
    secretEnv:
      NPM_TOKEN: CiQAcBjweQp70fQdHefg3+1XUiV+kwWJc/usCYSnHK6/kceVvDISTQCQlPnJ+dwlsKOmOB5j6Wp7QkXs/zeZahCylb7nvnGgUa/1h1qlK2IppruD5XdRLmO0OzujWNDfvmjfNNtZ46CQMrPf58T1ZV0hgP/P
