FROM cypress/base:10 AS test
WORKDIR /app

COPY package.json package-lock.json lerna.json ./
RUN npm ci

COPY tests ./tests
COPY --from=gcr.io/titicaca-ci/triple-frontend/build /app/packages ./packages

RUN npm run bootstrap

ENV CI=true
RUN npm test
