FROM node:15 AS docs-build
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

COPY . .

ARG TAG_NAME
RUN node ./docs/conf/package.json.js $TAG_NAME
RUN npm ci
RUN npm run build:storybook

FROM nginx:latest as docs-release

COPY --from=docs-build /app/docs/storybook-static /usr/share/nginx/html/
COPY ./docs/conf/nginx.conf /etc/nginx/nginx.conf
