FROM node:10 AS docs-build
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run bootstrap
RUN npm run build

RUN cd docs && npm run build

FROM nginx:latest as docs-release

COPY --from=docs-build /app/docs/storybook-static /usr/share/nginx/html/
COPY ./docs/conf/nginx.conf /etc/nginx/nginx.conf
