import type { Metadata } from 'next'

import StyledComponentsRegistry from '../lib/registry'
import ThemeProvider from '../lib/theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ThemeProvider>
          <body>{children}</body>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </html>
  )
}
