export const FOOTER_MIN_HEIGHTS = {
  MOBILE_WITH_APP_DOWNLOAD_BUTTON: 274,
  MOBILE_WITHOUT_APP_DOWNLOAD_BUTTON: 214,
  DESKTOP_WITH_APP_DOWNLOAD_BUTTON: 194,
  DESKTOP_WITHOUT_APP_DOWNLOAD_BUTTON: 174,
}

export const DESKTOP_MIN_WIDTH = 768
