name: PR Closed

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_API_URL_BASE: https://api.github.com/repos/${{ github.repository }}
  TAG_NAME: release-pr-${{ github.event.pull_request.number }}

jobs:
  delete-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag ref exist
        id: check-tag-ref
        # https://docs.github.com/en/free-pro-team@latest/rest/reference/git#get-a-reference
        run: |
          curl --url $GITHUB_API_URL_BASE/git/refs/tags/$TAG_NAME \
            -sI \
            -o /dev/null \
            -w "%{http_code}" \
            -H 'Authorization: token ${{ secrets.TRIPLE_BOT_GITHUB_TOKEN }}' \
          > status
          echo "::set-output name=status::$(cat status)"

      - name: Delete release tag of this pull request
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ env.TAG_NAME }}
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
