name: PR Closed

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_API_URL_BASE: https://api.github.com/repos/${{ github.repository }}
  TAG_NAME: release-pr-${{ github.event.pull_request.number }}
  # Node.js
  NODE_VERSION: '16.x'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  delete-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag ref exist
        id: check-tag-ref
        # https://docs.github.com/en/free-pro-team@latest/rest/reference/git#get-a-reference
        run: |
          curl --url $GITHUB_API_URL_BASE/git/refs/tags/$TAG_NAME \
            -sI \
            -o /dev/null \
            -w "%{http_code}" \
            -H 'Authorization: token ${{ secrets.TRIPLE_BOT_GITHUB_TOKEN }}' \
          > status
          echo "::set-output name=status::$(cat status)"

      - name: Delete release tag of this pull request
        if: ${{ steps.check-tag-ref.outputs.status == '200' }}
        # https://docs.github.com/en/rest/reference/git#delete-a-reference
        run: |
          curl --url $GITHUB_API_URL_BASE/git/refs/tags/$TAG_NAME \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization token ${{ secrets.TRIPLE_BOT_GITHUB_TOKEN }}" \
            -sI \
            -o /dev/null \
