name: Update CHANGELOG

on:
  pull_request:
    types:
      - labeled

env:
  COMMIT_USER_EMAIL: developer@triple-corp.com
  COMMIT_USER_NAME: triple-frontend[bot]
  CURRENT_VERSION: ${{ github.event.pull_request.milestone.title }}
  NODE_VERSION: 'lts/*'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'release' }}
    steps:
      - name: Check if a milestone exists on PR
        run: |
          if [[ $(echo ${{ github.event.pull_request.milestone }}) == "" ]]; then
            echo "마일스톤을 등록해 주세요."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
          cache: 'npm'

      - run: npm ci

      - name: Execute Changelog JavaScript
        run: node scripts/changelog.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push updated CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.TRIPLE_BOT_GITHUB_TOKEN }}
        run: |
          git config --local user.email "${{ env.COMMIT_USER_EMAIL }}"
          git config --local user.name "${{ env.COMMIT_USER_NAME }}"
          git add CHANGELOG.md
          git commit -m "Update ${{ env.CURRENT_VERSION }} CHANGELOG"
          git push
